#单机配置
spring:
  profiles: Single
server:
  port: ${PORT:8761}
  #port: ${PORT:${SERVER_PORT:0}} #随机端口
eureka:
  environment: dev  #test,prod
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    statusPageUrlPath: ${management.contextPath}/info
    healthCheckUrlPath: ${management.contextPath}/health
    hostname: localhost
    instanceId: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
  client:
   registerWithEureka: false
   fetchRegistry: false
   serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
   healthCheck: true
   region: default
   preferSameZoneEureka: true
   useDnsForFetchingServiceUrls: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false

logging:
  config: classpath:logback.xml